### ISSUE TITLE
srcset breaks the pog replacer

### ISSUE THREAD

**Issue by ReiFan49** [glasket/pogext#3]
title clearly says the problem.

with `srcset` attribute existing on the `img` element of the pogs, now you have to replace the `srcset` as well (either to empty one, or a proper replacement as well for the pog sizes, because there are about three variants according what i see)

I think this is the problem that everyone was looking the solution towards the (both FF and Chrome) extension. (and I'm too lazy to fork this out rn)

good luck with this project!

**Comment by adamisafk** [comment]
Started it on my fork https://github.com/adamisafk/pogext - also started on upgrading to manifest v3 (will need to overhaul background script as a service worker)

**Comment by glasket** [comment]
Sorry for the late reply, I've been busy with work and I haven't been using Twitch as often so I haven't directly seen breakages.

If the entire replacement is broken, then I doubt srcset would be the root cause since the extension actually replaces the img elements in their entirety using [Element.replaceWith()](https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith). This means that even if Twitch added srcset to the emote img elements, that would just get removed when the extension swapped the element with the custom node.

I'd have to look into it, which could take a few days due to work, but if the swapping is completely broken then my current guess would be that Twitch has changed their DOM layout in some way, either class names or the exact placement of elements could've been messed up at some point. Considering animated emotes got added, I wouldn't be surprised at all if this is what happened.

Edit: What I'll probably focus on, rather than immediately fixing the breakage, is adding a couple nice debug features like optional logging of failure points, because I'm guessing the issue is with the fetchElements function and just having a log spit out "Failed to find X element" would be great for immediately identifying why things are broken. I should probably also make it not fail-fast and instead just let it run even if it doesn't find everything it needs to observe. Not having the cardObserver shouldn't stop the entire extension.

Immediately afterwards I can fix up the specific problems that are happening, and go ahead and break up the main JS file a bit to make things easier to read.

**Comment by glasket** [comment]
Sorry for the long delay again, been really busy with work. My guess was right, the layout had changed which meant nothing was running at all. I pushed one small commit ([72ecaec](https://github.com/Glasket/pogext/commit/72ecaec4286a1bf5b54d1a0632d625089cc2f4b7)) that at least fixes the chat at a minimum. Card and picker fixes will take some more time, but at the very least I now know it's just DOM issues.

**Comment by glasket** [comment]
Should be resolved as of e2fcc90.

Updated version seems to be live on AMO already, should be live on Chrome within the next day or so too, depending on the review.
